### PR TITLE
Specify initial ML LDD

### PR DESCRIPTION
**Pull request by wkiri**
## Summary
The initial Machine Learning LDD contains these classes:
* `Trained_Machine_Learning_Model`: Specify model used to generate an ML product. 
  * Includes attributes (all required):
    * `trained_model_version_id`
    * `trained_model_name`
    * `trained_model_metric`
    * `trained_model_performance` 
  * and components:
    * `Training_Set` (required)
    * `Validation_Set` (optional)
    * `Test_Set` (optional)
* `Machine_Learning_Algorithm`: Specify the algorithm used to train the model.  
  *  Includes attributes (all required):
    * `algorithm_learning_style`: Choose one of `Supervised_Learning`, `Semisupervised_Learning`, or `Unsupervised_Learning` 
    * `algorithm_type`: Currently the only option available is `Convolutional_Neural_Network_Classifier`
    * `algorithm_name`
* `Image_Data_Set`: Abstract class, with three sub-classes:
  * `Training_Set`
  * `Validation_Set`
  * `Test_Set`
  * and these attributes (required):
    * `data_set_version_id`
    * `data_set_size`

## Test Data and/or Report
Regression tests in `test/` yield expected results:
* `test_mars_VALID.xml`: pass
* `test_mars_nodata_FAIL.xml`: fail (no training data specified)

### CODE REVIEW

**Review by rsjoyner — APPROVED** [review]
Reviewed and accepted modifications / changes.

**Review by myche — APPROVED** [review]
Looks good ... and includes some test data!  +1

**Review by jordanpadams — CHANGES_REQUESTED** [review]
@wkiri looks great! one thing I noticed was the ML LDD does not contain an overarching "parent class". This is something that has been encouraged for all discipline LDDs to help capture all components of an LDD together in a label. e.g. `<geom:Geometry>` for GEOM LDD and `` for IMG LDD. So maybe something like `<ml:Machine_Learning>`? Or something like that? I know it seems kind of repetitive (and maybe it is), but it seems to help make things much more straightforward when trying to implement portions of an LDD.

**Comment by wkiri** [comment]
@jordanpadams Great idea!  I've added a `Machine_Learning` parent class.  Could you take a look and let me know if this addresses your suggestion?

**Review by jordanpadams — APPROVED** [review]

**Comment by jordanpadams** [comment]
looks great! you are go for a merge if you are ready

**Comment by jordanpadams** [comment]
@wkiri ☝️

**Pull request merged**
