### PR TITLE
Updates for LDD 1.0.0.0 and PDS4 IM 1.17.0.0 Release

### PR DESCRIPTION
**Pull request by wkiri**
## Summary
This pull request addresses the request to support multiple performance metrics (pds-data-dictionaries/PDS4-LDD-Issue-Repo#179) and suggestions by Ed Guinness (pds-data-dictionaries/PDS4-LDD-Issue-Repo#182).  

In addition, these updates were made:
* Move the `Machine_Learning_Algorithm` to be a component of `Trained_Machine_Learning_Model`
* Create `Test_Performance` class to associate measures with scores and allow multiple performance measures to be supplied
* Add `algorithm_citation` attribute

Our goal is for this version of the ML LDD to be released as version 1.0.0.0.

## Test Data and/or Report
The regression tests all generate expected results:
* `test/test_mars_VALID.xml`: Pass 
* `test/test_mars_nodata_FAIL.xml`: Fail

## Related Issues
* Resolves pds-data-dictionaries/PDS4-LDD-Issue-Repo#179
* Resolves pds-data-dictionaries/PDS4-LDD-Issue-Repo#182

### CODE REVIEW

**Comment by wkiri** [comment]
Thanks, @jordanpadams !  What is your planned timeline for releasing 1.17.0.0?  (How much time do I have to fine-tune the ML LDD?)

**Comment by jordanpadams** [comment]
> Thanks, @jordanpadams ! What is your planned timeline for releasing 1.17.0.0? (How much time do I have to fine-tune the ML LDD?)

@wkiri will forward you the email, but 11/12 is the rough cutoff

**Comment by jordanpadams** [comment]
@wkiri as a heads up, we updated your branch with the latest PDS4 information model staged for release, so be sure to do a pull before you do any additional work in your repo.

additionally, you will notice your builds are failing. Per the error message you are seeing:

>      ERROR  [error.label.schematron]   line 16, 32: The attribute pds:Identification_Area/pds:information_model_version must be equal to the value '1.17.0.0'.

This is because for the test data, there are some rules that need to be followed so the CI/CD can auto-test with the latest version of the IM at each build cycle. See that info here:

https://pds-data-dictionaries.github.io/development/ldd-test.html?regression-test-data-rules#regression-test-data-rules

For this issue, see rule \#3

**Comment by wkiri** [comment]
@jordanpadams Thanks for the tips!  I updated the tests to use [IM_VERSION], and they are all passing.

It looks like with the 1.17.0.0 build, I am still seeing this message:
` >>> WARNING Header:  - New namespace id has been specified:ml`

However, if the `ml` namespace has been added, I assume this message would stop appearing.  Is that right?

**Comment by wkiri** [comment]
@jordanpadams I've added a user's guide to the `doc/` directory.

If this looks good to you, I'm ready to merge the PR.

**Review by jordanpadams — APPROVED** [review]

**Comment by jordanpadams** [comment]
👍

**Pull request merged**
